### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by YorickPeterse** [tov/libffi-rs#15]
Once libffi-sys-rs 1.0.0 is released (https://github.com/tov/libffi-sys-rs/issues/39), we can start working towards version 1.0.0 of the libffi crate. For this release it would be nice to also include ARMv7 support as added in https://github.com/tov/libffi-rs/pull/14, though that PR may need to be rebased after updating libffi-rs for libffi-sys-rs 1.0.0

## TODO

* [x] Release libffi-sys-rs 1.0.0
* [x] Update `master` to use this new version
* [x] ~~Merge https://github.com/tov/libffi-rs/pull/14~~ For a future release
* [ ] Publish to crates.io

**Comment by AndrewGaspar** [comment]
Glad to see you guys are putting out 1.0.0! Do you think this will be done soon? It would be really nice to get rid of the bindgen dependency - currently we're having to use an old version of bindgen in https://github.com/rsmpi/rsmpi.git because of the version 0.9.0 is using.

**Comment by YorickPeterse** [comment]
@AndrewGaspar This issue is blocked by https://github.com/tov/libffi-sys-rs/issues/39, which I can finish once I get a hold of @tov :smiley:

**Comment by YorickPeterse** [comment]
Version 1.0 is now released.

**Comment by AndrewGaspar** [comment]
Thank you for doing this - much appreciated!
